#define HELLOS_PROJECT_WIN32_BAREBONES() (0)
#define HELLOS_PROJECT_WIN32_DX11_TRIANGLE() (1)

#define BUILD_PROJECT() (HELLOS_PROJECT_WIN32_DX11_TRIANGLE())

#if BUILD_PROJECT() == HELLOS_PROJECT_WIN32_BAREBONES()
#include "Win32_Barebones.cpp"
#elif BUILD_PROJECT() == HELLOS_PROJECT_WIN32_DX11_TRIANGLE()
#include "Win32_DX11_Triangle.cpp"
#else
#error "ERROR: Undefined BUILD_PROJECT!!"
#endif

